// vue/src/components/Board.vue
<template>
    <ul>
        <Cell v-for="(item, index) in cellList"
            :data-index="index"
            :key="index"
            :playedBy="plays[index]"
            :winningCell="winningCombo.includes(index)"
            :onCellClick="handleCellClick" />
    </ul>
</template>

<script>
import Cell from './Cell';
import { checkWinner } from '../../../shared/gameplay.js';

export default {
  name: 'Board',
  props: {
      plays: Array,
      winningCombo: Array,
      player: String,
      onChangePlayer: Function,
      setWinner: Function,
      setPlays: Function,
      setWinningCombo: Function
  },
  components: {
      Cell
  },
  setup(props) {
    const cellList = Array(9).fill();

    function isTie(plays) {
        return !plays.includes(undefined);
    }

    function handleCellClick(e) {
        const clickedIndex = e.target.dataset.index;
        const newPlays = props.plays.map((v, i) => {
            return i === parseInt(clickedIndex) ? props.player : v;
        });

        if(isTie(newPlays)) {
            props.setWinner('tie!');
        }

        if(!props.plays[clickedIndex] && !props.winningCombo.length) {
            props.setPlays(newPlays);
            if(isTie(newPlays)) {
                props.setWinner('tie!')
                return
            }else if(checkWinner(newPlays, props.player, props.setWinningCombo)) {
                props.setWinner(props.player);
                return
            }
            props.onChangePlayer();
        }
    }

    return {
        cellList,
        handleCellClick
    }
  }
}

</script>

// react/src/components/Board.js
import React, { useEffect } from 'react';
import Cell from './Cell';
import { winningCombos } from '../constants';

export default function Board({ onChangePlayer, player, setWinner, winningCombo, setWinningCombo, plays, setPlays }) {

    function isTie(plays) {
        return !plays.includes(undefined);
    }

    function handleCellClick(e){
        const clickedIndex = e.target.dataset.index;
        const newPlays = plays.map((v, i) => {
            return i === parseInt(clickedIndex) ? player : v;
        });

        if(isTie(newPlays)) {
            setWinner('tie!')
        }

        if(!plays[clickedIndex] && !winningCombo.length) {
            setPlays(newPlays);
            if(isTie(newPlays)) {
                setWinner('tie!')
                return
            }else if(checkWinner(newPlays)) {
                setWinner(player);
                return
            }
            onChangePlayer();
        }
    }

    function checkWinner(newPlays) {
        return winningCombos.some((combo) => {
            const winningCombo = combo.every((index) => {
                return newPlays[index] === player;
            });
            if(winningCombo) {
                setWinningCombo(combo);
            }
            return winningCombo;
        });
    }

    useEffect(() => {
        console.dir(plays);
    }, [plays]);

    const cellList = Array(9).fill().map((_, index) => {
        return <Cell key={index} data-index={index} playedBy={plays[index]} winningCell={winningCombo.includes(index)} onCellClick={handleCellClick}>{index}</Cell>
    });

    return (
        <ul>
            {cellList}
        </ul>
    );
}
